spring.application.name=LoanApplication

# Database Connection
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings for PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SSL Requirement for Neon
spring.datasource.hikari.connection-test-query=SELECT 1

# File Upload Limits
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Ensure Spring knows where to look for the uploads folder
spring.web.resources.static-locations=classpath:/static/,file:uploads/
#spring.web.resources.static-locations=file:uploads/

spring.mail.host={SPRING_SMPT}
spring.mail.port={SPRING_MAIL_PORT}
# This reads from the Render Environment Variable
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth={SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable={SMTP_ENABLE}
spring.mail.properties.mail.debug={SMTP_DEBUG}